version: '3'
services:
  redis:
    image: redis:6.2-alpine
    expose:
      - 6379

  base_app:
    build: .
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      redis:
        condition: service_started

  app:
    extends: base_app
    command: python main.py

  worker:
    extends: base_app
    command: rq worker --with-scheduler --url redis://redis:6379/0